# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Object-Accessor-Inheritable
version:      0.01
version_from: lib/Object/Accessor/Inheritable.pm
installdirs:  site
requires:
    Object::Accessor:              0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
